server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/usuarios/**
            - id: sales-service
              uri: lb://sales-service
              predicates:
                - Path=/api/ventas/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/productos/**
            - id: sales-service
              uri: lb://sales-service
              predicates:
                - Path=/api/ventas/**
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: ERROR